FROM tomcat:9-jre8
MAINTAINER <a href="mailto:e.h.juerrens@52north.org">J&uuml;rrens, Eike Hinderk</a>

ENV MAVEN_VERSION 3.3.9
ENV MAVEN_HOME /usr/share/maven

RUN rm -rfv /usr/local/tomcat/webapps/docs &&\
    rm -rfv /usr/local/tomcat/webapps/examples &&\
    rm -rfv /usr/local/tomcat/webapps/host-manager &&\
    rm -rfv /usr/local/tomcat/webapps/manager &&\
    rm -fv /usr/local/tomcat/webapps/ROOT/tomcat* &&\
    find /usr/local/tomcat/webapps/ROOT/* -maxdepth 0  -type f -print0| xargs -0 rm -v &&\
    apt-get autoremove --purge --assume-yes && apt-get clean --assume-yes &&\
    rm -rf /var/cache/apt/archives &&\
    rm -rf /root/.m2 &&\
    rm -rf /var/lib/apt/lists/*

COPY webapp/target/52n-sos-webapp /usr/local/tomcat/webapps/52n-sos-webapp


COPY docker/dakamon/tomcat-index.html /usr/local/tomcat/webapps/ROOT/index.html
# config uses postgrest:postgres @db
COPY docker/dakamon/datasource.properties /usr/local/tomcat/webapps/52n-sos-webapp/WEB-INF/
COPY docker/dakamon/configuration.db /usr/local/tomcat/webapps/52n-sos-webapp/
COPY docker/dakamon/application.properties /usr/local/tomcat/webapps/52n-sos-webapp/WEB-INF/classes/

WORKDIR /usr/local/tomcat

ENV JAVA_OPTS="-XX:PermSize=4096m -XX:MaxPermSize=3072m"